/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author Lanaya
 */
public class SmartCalculator extends javax.swing.JFrame {
    
    /**
     * Variables to hold operands, operator, calculator display and calculated
     * result
     */
    private double firstOperand, secondOperand;
    private char operator;
    private String displayResult = "0";
    private double result = 0;
    
    /**
     * Creates new form SmartCalculator
     */
    public SmartCalculator() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcDisplayTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnDivide = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtnMultiply = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnSubtract = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtnDot = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jBtnEqual = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setFont(new java.awt.Font("Carlito", 0, 14)); // NOI18N
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(200, 200));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        calcDisplayTextField.setEditable(false);
        calcDisplayTextField.setFont(new java.awt.Font("Carlito", 0, 14)); // NOI18N
        calcDisplayTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        calcDisplayTextField.setText("0");
        calcDisplayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcDisplayTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(calcDisplayTextField, java.awt.BorderLayout.NORTH);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn7);

        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn8);

        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn9);

        jBtnDivide.setText("/");
        jBtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivideActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnDivide);

        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn4);

        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn5);

        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn6);

        jBtnMultiply.setText("*");
        jBtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMultiplyActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnMultiply);

        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn1);

        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn2);

        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn3);

        jBtnSubtract.setText("-");
        jBtnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubtractActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSubtract);

        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn0);

        jBtnDot.setText(".");
        jBtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDotActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnDot);

        jBtnAdd.setText("+");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnAdd);

        jBtnEqual.setText("=");
        jBtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnEqual);

        jBtnClear.setText("C");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnClear);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcDisplayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcDisplayTextFieldActionPerformed
        calcDisplayTextField.setText(displayResult);
    }//GEN-LAST:event_calcDisplayTextFieldActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        if(displayResult == "0")
        {
            displayResult = "7";
        }
        else
        {
            displayResult += "7";
        }
        calcDisplayTextField.setText(displayResult);
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        if (displayResult == "0") {
            displayResult = "8";
        }
        else
        {
            displayResult += "8";
        }
        calcDisplayTextField.setText(displayResult);
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        if (displayResult == "0") {
            displayResult = "9";
        }
        else
        {
            displayResult += "9";
        }
        calcDisplayTextField.setText(displayResult);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        if (displayResult == "0") {
            displayResult = "4";
        }
        else
        {
            displayResult += "4";
        }
        calcDisplayTextField.setText(displayResult);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        if (displayResult == "0") {
            displayResult = "5";
        }
        else
        {
            displayResult += "5";
        }
        calcDisplayTextField.setText(displayResult);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        if (displayResult == "0") {
            displayResult = "6";
        }
        else
        {
            displayResult += "6";
        }
        calcDisplayTextField.setText(displayResult);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        if (displayResult == "0") {
            displayResult = "1";
        }
        else
        {
            displayResult += "1";
        }
        calcDisplayTextField.setText(displayResult);
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        if (displayResult == "0") {
            displayResult = "2";
        }
        else
        {
            displayResult += "2";
        }
        calcDisplayTextField.setText(displayResult);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        if (displayResult == "0") {
            displayResult = "3";
        }
        else
        {
            displayResult += "3";
        }
        calcDisplayTextField.setText(displayResult);
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        if (displayResult == "0") {
            displayResult = "0";
        }
        else
        {
            displayResult += "0";
        }
        calcDisplayTextField.setText(displayResult);
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDotActionPerformed
        if (displayResult == "0") {
            displayResult = ".";
        }
        else
        {
            displayResult += ".";
        }
        calcDisplayTextField.setText(displayResult);
    }//GEN-LAST:event_jBtnDotActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        operator = '+';   
        if (firstOperand == 0)
        {
            firstOperand = Double.parseDouble(displayResult);
            displayResult += operator;
            calcDisplayTextField.setText(displayResult);
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqualActionPerformed
        int displayLength = displayResult.length();
        int operatorIndex = 0 ;
        if (!displayResult.endsWith(Character.toString('+')) && operator == '+')
        {
            operatorIndex = displayResult.indexOf(Character.toString('+'));
            secondOperand = Double.parseDouble(displayResult.substring(operatorIndex+1));
            System.out.println(displayResult + " len " + displayLength);
            System.out.println("opin " + operatorIndex);    
            System.out.println(" sec " + secondOperand);
        }
        else if (!displayResult.endsWith(Character.toString('-'))  
                && operator == '-')
        {
            operatorIndex = displayResult.indexOf(Character.toString('-'));
            secondOperand = Double.parseDouble(displayResult.substring(operatorIndex+1));
            System.out.println(displayResult + " len " + displayLength);
            System.out.println("opin " + operatorIndex);    
            System.out.println(" sec " + secondOperand);
        }
        else if (!displayResult.endsWith(Character.toString('*'))
                 && operator == '*')
        {
            operatorIndex = displayResult.indexOf(Character.toString('*'));
            secondOperand = Double.parseDouble(displayResult.substring(operatorIndex+1));
            System.out.println(displayResult + " len " + displayLength);
            System.out.println("opin " + operatorIndex);    
            System.out.println(" sec " + secondOperand);
        }
        else if (!displayResult.endsWith(Character.toString('/'))
                 && operator == '/')
        {
            operatorIndex = displayResult.indexOf(Character.toString('/'));
            secondOperand = Double.parseDouble(displayResult.substring(operatorIndex+1));
            System.out.println(displayResult + " len " + displayLength);
            System.out.println("opin " + operatorIndex);    
            System.out.println(" sec " + secondOperand);;
        }
               
        switch(operator)
        {
            case '+':
                result = firstOperand + secondOperand;
                break;
            case '-':
                result = firstOperand - secondOperand;
                break;
            case '*':
                result = firstOperand * secondOperand;
                break;
            case '/':
                result = firstOperand / secondOperand;
                break;
            case '\0':
                result = 0;
        }
        firstOperand = 0;
        secondOperand = 0;
        calcDisplayTextField.setText(Double.toString(result));
    }//GEN-LAST:event_jBtnEqualActionPerformed

    private void jBtnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubtractActionPerformed
        operator = '-';   
        if (firstOperand == 0)
        {
            firstOperand = Double.parseDouble(displayResult);
            displayResult += operator;
            calcDisplayTextField.setText(displayResult);
        }
    }//GEN-LAST:event_jBtnSubtractActionPerformed

    private void jBtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMultiplyActionPerformed
        operator = '*';
        if (firstOperand == 0)
        {
            firstOperand = Double.parseDouble(displayResult);
            displayResult += operator;
            calcDisplayTextField.setText(displayResult);
        }
    }//GEN-LAST:event_jBtnMultiplyActionPerformed

    private void jBtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivideActionPerformed
        operator = '/';
        if (firstOperand == 0)
        {
            firstOperand = Double.parseDouble(displayResult);
            displayResult += operator;
            calcDisplayTextField.setText(displayResult);
        }
    }//GEN-LAST:event_jBtnDivideActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        operator = '\0';
        firstOperand = 0;
        secondOperand = 0;
        result = 0;
        displayResult = "0";
        calcDisplayTextField.setText("0");
    }//GEN-LAST:event_jBtnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartCalculator().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calcDisplayTextField;
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnDivide;
    private javax.swing.JButton jBtnDot;
    private javax.swing.JButton jBtnEqual;
    private javax.swing.JButton jBtnMultiply;
    private javax.swing.JButton jBtnSubtract;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
